project:
  type: website

website:
  title: "MyBlog"
  navbar:
    right:
      - about.qmd
      - icon: instagram
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css

editor: visual

